# Generated by Django 4.0.4 on 2022-05-11 07:41

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=10)),
                ('character', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('user_seed', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('phonenum', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=10)),
                ('account_num', models.CharField(max_length=30)),
                ('holder', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_point', models.IntegerField()),
                ('total_point', models.IntegerField()),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('delivery', models.CharField(blank=True, max_length=10)),
                ('delivery_num', models.CharField(blank=True, max_length=20)),
                ('is_confirm', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=40)),
            ],
        ),
    ]
